APPS-752 dxApi utility to clone file, APPS-754 dxApi utility to clone applet.
dnanexus/dxScala pull request #55
Opened 2021-08-09 14:08 UTC by r-i-v-a

2021-08-09 14:11 UTC, r-i-v-a commented on api/src/main/scala/dx/api/DxApi.scala
> +  def cloneObject(id: String,
Question -- I eventually want the ability to clone both files and applets to the current project, if not already there (see https://jira.internal.dnanexus.com/browse/APPS-752 , https://jira.internal.dnanexus.com/browse/APPS-754), it seems like projectClone can take objects of different types, so could it be done this way? @jdidion

2021-08-09 14:13 UTC, r-i-v-a commented on api/src/main/scala/dx/api/DxApi.scala
> +      // TODO: Could it work this way for both files and applets?
Also, I looked at cloneAsset as an example, but want to exclude the parts that are only needed when cloning a record -- is it correct? @jdidion

2021-08-11 16:43 UTC, jdidion commented
Please update the function name to `cloneDataObject`. "Data object" is platform terminology for any object that exists within the context of a project (e.g. file, record, applet, workflow).

2021-08-16 14:44 UTC, r-i-v-a commented
> Please update the function name to `cloneDataObject`. "Data object" is platform terminology for any object that exists within the context of a project (e.g. file, record, applet, workflow).

Done.

2021-08-16 18:59 UTC, jdidion requested changes

2021-08-17 11:44 UTC, r-i-v-a commented on api/src/main/scala/dx/api/DxApi.scala
> +      val request = Map("objects" -> JsArray(JsString(id)),
https://documentation.dnanexus.com/developer/api/data-containers/cloning#api-method-class-xxxx-clone

2021-08-17 11:46 UTC, r-i-v-a commented on api/src/main/scala/dx/api/DxApi.scala
> +      val request = Map("objects" -> JsArray(JsString(id)),
Setting parents -> true in both functions.

2021-08-17 15:39 UTC, jdidion commented on api/src/main/scala/dx/api/DxApi.scala
> +                        "parents" -> JsBoolean(true))
Minor comment - you can use `JsTrue` rather than `JsBoolean(true)`

2021-08-17 15:39 UTC, jdidion approved these changes

2021-08-18 12:48 UTC, merged