APPS-803 Sonatype Nexus publishing setup readme.
dnanexus/dxScala pull request #67
Opened 2021-09-10 15:18 UTC by r-i-v-a

2021-09-10 16:02 UTC, jdidion approved these changes, later dismissed

2021-09-11 09:39 UTC, commandlinegirl requested changes

2021-09-11 09:39 UTC, commandlinegirl commented on DEVELOPING.md
> +1. From the release branch, run `sbt 'project <name>' publishSigned -DreleaseTarget=sonatype` for each project being released. You will need to have completed the "Sonatype Nexus publishing setup" in
Do we have a GitHub action workflow for this (or are planning to add)?

2021-09-11 09:39 UTC, commandlinegirl commented on DEVELOPING.md
> +### Sonatype Nexus publishing setup
Please check my comments in https://github.com/dnanexus-rnd/wdlTools/pull/178 for review. Thanks!

2021-09-14 16:21 UTC, r-i-v-a commented
From discussion, agreed to merge documentation of current process

Jiras to publish to GitHub packages https://jira.internal.dnanexus.com/browse/APPS-809 , https://jira.internal.dnanexus.com/browse/APPS-808

2021-09-15 08:05 UTC, commandlinegirl approved these changes

2021-09-15 08:09 UTC, commandlinegirl approved these changes, later dismissed

2021-09-15 08:09 UTC, commandlinegirl commented on DEVELOPING.md
> +- Have `dnanexus`'s password for [Sonatype Nexus repository manager](https://oss.sonatype.org/#stagingRepositories). Riva Nathans and John Didion have the password.
```suggestion

We use [Sonatype Nexus repository manager](https://oss.sonatype.org/#stagingRepositories) to release artifacts. In order to set it up:

- Have `dnanexus`'s password for Sonatype. Riva Nathans and John Didion have the password.
```

2021-09-16 10:20 UTC, commandlinegirl approved these changes
LGTM, thank you, Riva!

2021-09-16 11:22 UTC, merged